# Generated by Django 5.0.3 on 2024-04-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bname", models.CharField(max_length=20)),
                ("author", models.CharField(max_length=10)),
                ("desc", models.TextField(max_length=100)),
                ("price", models.IntegerField(default=0)),
                ("amazon_link", models.CharField(max_length=150)),
            ],
        ),
    ]
