# Generated by Django 5.0.3 on 2024-04-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookstore", "0004_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Countries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("published", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="published_countries",
            field=models.ManyToManyField(to="bookstore.countries"),
        ),
    ]
